# Профиль для локальной разработки без PostgreSQL (H2 in-memory)
spring:
  datasource:
    url: jdbc:h2:mem:cardb;DB_CLOSE_DELAY=-1;MODE=PostgreSQL;DATABASE_TO_LOWER=TRUE
    driver-class-name: org.h2.Driver
    username: sa
    password:

  flyway:
    url: jdbc:h2:mem:cardb;DB_CLOSE_DELAY=-1;MODE=PostgreSQL;DATABASE_TO_LOWER=TRUE
    user: sa
    password:
    enabled: true

spring.jpa.database-platform: org.hibernate.dialect.H2Dialect
